export const CHECK_BALANCE = 'CHECK_BALANCE';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const REFRESH_PLAYS = 'REFRESH_PLAYS';

// export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
// export const USER_BUSINESS_MAPPING_CREATED = 'USER_BUSINESS_MAPPING_CREATED';
// export const SET_UNCONFIRMED_EMAIL = 'SET_UNCONFIRMED_EMAIL';
// export const UPDATE_NEW_BUSINESS = 'UPDATE_NEW_BUSINESS';
// export const USER_BUSINESS_TYPE = 'USER_BUSINESS_TYPE';
// export const SET_USER_ALL_BUSINESSES = 'SET_USER_ALL_BUSINESSES';